M48
; DRILL file KiCad 10.0.5 date 2026-09-28T21:52:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T21:52:01+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X57.25Y85.495
X71.15Y85.495
X76.25Y85.495
X90.15Y85.495
T2
X4.0Y86.0
X4.0Y4.0
X96.0Y86.0
X96.0Y4.0
M30
